opresent-cms/src/main/java/ru/opresent/web/cms/bean/image_synchronization/ImageFileSyncPushEndPoint.java
package ru.opresent.web.cms.bean.image_synchronization;

import org.primefaces.push.annotation.OnMessage;
import org.primefaces.push.annotation.PushEndpoint;
import ru.opresent.web.cms.util.JacksonJsonEncoder;

/**
 * User: artem
 * Date: 07.12.14
 * Time: 15:17
 */
@PushEndpoint(ImageFileSynchronizationBean.PUSH_CHANNEL_PATH)
public class ImageFileSyncPushEndPoint {

    @OnMessage(encoders = {JacksonJsonEncoder.class})
    public ImageFileSyncSession onMessage(ImageFileSyncSession data) {
        return data;
    }

}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/image_synchronization/ImageFileSyncSession.java
package ru.opresent.web.cms.bean.image_synchronization;

import java.io.Serializable;
import java.util.Date;

/**
 * User: artem
 * Date: 16.12.14
 * Time: 5:28
 */
public class ImageFileSyncSession implements Serializable {

    private int totalCount;
    private int processedCount;
    private String message;

    public int getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(int totalCount) {
        this.totalCount = totalCount;
    }

    public int getProcessedCount() {
        return processedCount;
    }

    public void setProcessedCount(int processedCount) {
        this.processedCount = processedCount;
    }

    public int getProcessedPercent() {
        return totalCount == 0 ? 0 : processedCount * 100 / totalCount;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = "[" + new Date() + "] " + message;
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/image_synchronization/ImageFileSynchronizationBean.java
package ru.opresent.web.cms.bean.image_synchronization;

import org.apache.commons.lang3.exception.ExceptionUtils;
import org.primefaces.push.EventBus;
import org.primefaces.push.EventBusFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.component.api.image.ImageFileProcessMode;
import ru.opresent.core.synchronization.ImageFileSynchronizer;
import ru.opresent.core.synchronization.ImageSynchronizationListener;

import javax.annotation.Resource;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * User: artem
 * Date: 16.07.14
 * Time: 23:48
 */
@Component("imageFileSynchronizationBean")
@Scope("view")
public class ImageFileSynchronizationBean implements ImageSynchronizationListener, Serializable {

    public static final String PUSH_CHANNEL_PATH = "/pages/image_synchronization/image_synchronization";

    @Resource(name = "imageFileSynchronizer")
    private transient ImageFileSynchronizer imageFileSynchronizer;

    private ImageFileProcessMode imageFileProcessMode = ImageFileProcessMode.LIGHT;
    private ImageFileSyncSession syncSession;

    public void start() {
        syncSession = new ImageFileSyncSession();

        final ImageSynchronizationListener listener = this;
        new Thread(new Runnable() {
            @Override
            public void run() {
                imageFileSynchronizer.synchronize(listener);
            }
        }).start();
    }

    @Override
    public void cleaningStarted() {
        syncSession.setMessage("Cleaning started");
        pushData();
    }

    @Override
    public void cleaningFinished() {
        syncSession.setMessage("Cleaning finished");
        pushData();
    }

    @Override
    public void error(Exception e) {
        syncSession.setMessage(ExceptionUtils.getStackTrace(e));
        pushData();
    }

    @Override
    public void consumeTotalCount(int totalCount) {
        syncSession.setTotalCount(totalCount);
        syncSession.setMessage("Total count: " + totalCount);
        pushData();
    }

    @Override
    public void consumeProcessedCount(int processedCount) {
        syncSession.setProcessedCount(processedCount);
        syncSession.setMessage("Processed count: " + processedCount);
        pushData();
    }

    @Override
    public void complete() {
        syncSession.setMessage("Synchronization complete.");
        pushData();
    }

    @Override
    public ImageFileProcessMode getImageFileProcessMode() {
        return imageFileProcessMode;
    }

    private void pushData() {
        EventBus eventBus = EventBusFactory.getDefault().eventBus();
        eventBus.publish(PUSH_CHANNEL_PATH, syncSession);
    }

    // setters & getters

    public void setImageFileProcessMode(ImageFileProcessMode imageFileProcessMode) {
        this.imageFileProcessMode = imageFileProcessMode;
    }

    public List<ImageFileProcessMode> getAvailableImageFileProcessModes() {
        return Arrays.asList(ImageFileProcessMode.values());
    }

    public String getPushChannelPath() {
        return PUSH_CHANNEL_PATH;
    }

}

opresent-cms/src/main/webapp/pages/image_synchronization/image_synchronization.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xml:lang="en" lang="en" xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core">

    <ui:define name="windowTitle">
        <h:outputText value="Images files synchronization"/>
    </ui:define>

    <ui:define name="content">
        <style type="text/css">
            input {
                width: 500px;
            }
            div#logMsgs {
                text-align: left;
            }
            .ui-scrollpanel {
                height:500px
            }
        </style>

        <h3>Images files synchronization</h3>

        <h:form>

            <h:panelGrid columns="2">

                <h:outputText value="Process mode"/>
                <p:selectOneMenu value="#{imageFileSynchronizationBean.imageFileProcessMode}">
                    <f:selectItems value="#{imageFileSynchronizationBean.availableImageFileProcessModes}"
                                   var="processMode"
                                   itemLabel="#{processMode.name()}" itemValue="#{processMode}"/>
                </p:selectOneMenu>

            </h:panelGrid>

            <h:panelGrid id="buttonsPanel" styleClass="buttonsPanel" columns="3">
                <p:commandButton value="Start" action="#{imageFileSynchronizationBean.start()}"/>
            </h:panelGrid>

        </h:form>

        <p:progressBar widgetVar="progressBarWidget" value="0" labelTemplate="{value}%"/>

        <p:scrollPanel id="syncProductPanel" mode="native">
            <div id="logMsgs"></div>
        </p:scrollPanel>

        <p:socket onMessage="handleSyncData" channel="#{imageFileSynchronizationBean.pushChannelPath}"/>

        <script type="text/javascript">
            //<![CDATA[
            function handleSyncData(data) {
                PF('progressBarWidget').setValue(data.processedPercent);

                var logMsgs = $("div#logMsgs");
                logMsgs.append($("<p>" + data.message + "</p>"));
                var scrollPanel = $("div.ui-scrollpanel");
                scrollPanel.scrollTop(logMsgs.height() - scrollPanel.height());
            }
            //]]>
        </script>
    </ui:define>

</ui:composition>