opresent-cms/src/main/java/ru/opresent/web/cms/bean/ImageFileBean.java
package ru.opresent.web.cms.bean;

import org.primefaces.model.UploadedFile;
import org.springframework.stereotype.Component;
import ru.opresent.core.component.api.image.ImageConstraints;
import ru.opresent.core.domain.image.HasCopyrightOption;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.service.api.ImageService;
import ru.opresent.web.cms.converter.UploadedFileToImageConverter;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.Resource;
import java.util.List;

/**
 * User: artem
 * Date: 31.03.14
 * Time: 0:32
 */
@Component("imageFileBean")
public class ImageFileBean {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.image_file";

    @Resource(name = "imageConstraints")
    private ImageConstraints imageConstraints;

    @Resource(name = "imageService")
    private ImageService imageService;

    @Resource(name = "uploadedFileToImageConverter")
    private UploadedFileToImageConverter uploadedFileToImageConverter;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    public String getAllowTypesPattern() {
        StringBuilder pattern = new StringBuilder("/(\\.|\\/)(");

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                pattern.append("|");
            }
            pattern.append(formats.get(i));
        }

        pattern.append(")$/");
        return pattern.toString();
    }

    public String getInvalidFileMessage() {
        StringBuilder formatsStr = new StringBuilder();

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                formatsStr.append(", ");
            }
            formatsStr.append(formats.get(i));
        }

        return messageManager.getMessage(BUNDLE_NAME, "invalid_file_client_msg", formatsStr.toString());
    }

    /**
     * @return size limit in bytes
     */
    public int getSizeLimit() {
        return imageConstraints.getMaxSize();
    }

    public String getInvalidSizeMessage() {
        int maxSize = imageConstraints.getMaxSize();
        return messageManager.getMessage(BUNDLE_NAME, "invalid_size_client_msg", maxSize / 1024, maxSize / 1024 / 1024);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse) {
        return saveImage(uploadedFile, imageUse, HasCopyrightOption.INHERIT_FROM_IMAGE_USE);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse, HasCopyrightOption hasCopyrightOption) {
        Image image = uploadedFileToImageConverter.convert(uploadedFile, imageUse, hasCopyrightOption);
        return imageService.save(image);
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/product/ProductBean.java
package ru.opresent.web.cms.bean.product;


import org.primefaces.event.FileUploadEvent;
import org.primefaces.json.JSONObject;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.CoreException;
import ru.opresent.core.domain.*;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.service.api.*;
import ru.opresent.core.util.IdentifiableList;
import ru.opresent.web.cms.Deleter;
import ru.opresent.web.cms.bean.ImageFileBean;
import ru.opresent.web.cms.component.dialog.SelectCategoryListDialog;
import ru.opresent.web.cms.component.dialog.SelectColorListDialog;
import ru.opresent.web.cms.component.galleria.ImagesListModel;
import ru.opresent.web.cms.component.rich_text.RichTextContainer;
import ru.opresent.web.cms.converter.IdentifiableConverter;
import ru.opresent.web.cms.util.MessageManager;
import ru.opresent.web.cms.util.WebUtils;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.context.FacesContext;
import javax.validation.ConstraintViolationException;
import java.io.Serializable;
import java.text.MessageFormat;
import java.util.*;

/**
 * User: artem
 * Date: 04.11.13
 * Time: 15:06
 */
@Component("productBean")
@Scope("view")
public class ProductBean implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.product.product";

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    @Resource(name = "productService")
    private transient ProductService productService;

    @Resource(name = "productTypeService")
    private transient ProductTypeService productTypeService;

    @Resource(name = "sizeService")
    private transient SizeService sizeService;

    @Resource(name = "categoryService")
    private transient CategoryService categoryService;

    @Resource(name = "colorService")
    private transient ColorService colorService;

    @Resource(name = "productLabelService")
    private transient ProductLabelService productLabelService;

    @Resource(name = "imageFileBean")
    private transient ImageFileBean imageFileBean;

    @Resource(name = "productStatusService")
    private transient ProductStatusService productStatusService;

    @Resource(name = "searchService")
    private transient SearchService searchService;

    private Product product;

    private SelectCategoryListDialog selectCategoryListDialog;
    private SelectColorListDialog selectColorListDialog;

    private ImagesListModel viewsListModel;

    private Tab currentTab = Tab.MAIN;

    @PostConstruct
    private void init() {
        Integer tabIndex = WebUtils.getIntegerRequestParameter("tab");
        currentTab = tabIndex == null ? currentTab : Tab.valueOfIndex(tabIndex);

        Long productId = WebUtils.getLongRequestParameter("id");
        if (productId == null) {
            product = new Product();
            product.setVisible(true);
        } else {
            product = productService.load(productId);
        }

        selectCategoryListDialog = new SelectCategoryListDialog(new SelectCategoryListDialogHandler());
        selectColorListDialog = new SelectColorListDialog(new SelectColorListDialogHandler());

        viewsListModel = new ImagesListModel();
        viewsListModel.setImages(product.getViews());
    }

    public String save() {
        try {
            product = productService.save(product);
        } catch (ConstraintViolationException e) {
            messageManager.addErrorMessage(e);
            return null;
        }
        searchService.updateIndexAfterProductSave(product.getId());

        messageManager.addInfoMessage(BUNDLE_NAME, "save_success", product.getName());
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);

        return "product_list?faces-redirect=true";
    }

    public void handlePreviewImageUpload(FileUploadEvent event) {
        Image image = imageFileBean.saveImage(event.getFile(), ImageUse.PRODUCT_PREVIEW_IMAGE);
        product.setPreview(image);
    }

    public void handleViewImageUpload(FileUploadEvent event) {
        Image image = imageFileBean.saveImage(event.getFile(), ImageUse.PRODUCT_VIEW_IMAGE);
        product.getViews().add(image);

        viewsListModel.setImages(product.getViews());
        viewsListModel.selectLastImage();
    }

    public void moveViewImage(ViewMovingType movingType) {
        Image movingView = viewsListModel.getSelectedImage();
        List<Image> views = product.getViews();
        if (!views.contains(movingView)) {
            throw new CoreException("Moving view not contains in views list!");
        }
        int movingViewIndex = views.indexOf(movingView);
        boolean isFirst = movingViewIndex == 0;
        boolean isLast = movingViewIndex == views.size() - 1;

        if ((isFirst && (movingType == ViewMovingType.BEGIN || movingType == ViewMovingType.LEFT)) ||
            (isLast && (movingType == ViewMovingType.RIGHT || movingType == ViewMovingType.END))) {
            throw new IllegalArgumentException(
                    MessageFormat.format("Can not move view to {0} because it is {1}! [view: {2}]",
                            movingType, isFirst ? "first" : "last", movingView));
        }

        int newIndex;
        switch (movingType) {
            case BEGIN: newIndex = 0;
                break;
            case LEFT: newIndex = movingViewIndex - 1;
                break;
            case RIGHT: newIndex = movingViewIndex + 1;
                break;
            case END: newIndex = views.size() - 1;
                break;
            default:
                throw new IllegalArgumentException("Unknown element of " +
                        ViewMovingType.class.getName() + ": " + movingType);
        }

        views.remove(movingView);
        views.add(newIndex, movingView);
        viewsListModel.setImages(views);
        viewsListModel.setSelectedImage(movingView);
    }

    public void cleanProductLabel() {
        product.setLabel(null);
        product.setLabelNote(null);
    }

    public void defaultStatusNote() {
        ProductStatusInfo statusInfo = productStatusService.getAll().get(product.getStatus());
        product.setStatusNote(statusInfo == null ? null : statusInfo.getDefaultNote());
    }

    public void defaultLabelNote() {
        product.setLabelNote(product.getLabel().getDefaultNote());
    }

    private void deleteViewImage() {
        Image deletingView = viewsListModel.getSelectedImage();
        int deletingViewIndex = viewsListModel.getImages().indexOf(deletingView);
        boolean isLastViewDeleting = deletingViewIndex == viewsListModel.getImages().size() - 1;

        List<Image> views = product.getViews();
        views.remove(deletingView);
        viewsListModel.setImages(views);
        if (!views.isEmpty()) {
            if (isLastViewDeleting) {
                viewsListModel.selectLastImage();
            } else {
                viewsListModel.setSelectedImage(views.get(deletingViewIndex));
            }
        }
    }

    public ProductStatus getProductStatus() {
        return product.getStatus();
    }

    public void setProductStatus(ProductStatus status) {
        product.setStatus(status);
        if (status != ProductStatus.FOR_ORDER) {
            product.setProductionTime(null);
        }
    }

    // setters & getters

    public boolean isAddition() {
        return product.getId() == Identifiable.NOT_SAVED_ID;
    }

    public boolean isEditing() {
        return product.getId() != Identifiable.NOT_SAVED_ID;
    }

    public Tab getCurrentTab() {
        return currentTab;
    }

    public void setCurrentTab(Tab currentTab) {
        this.currentTab = currentTab;
    }

    /**
     * Get tabs info as JSON:<br/>
     * <pre>
     * {
     *     "nameToIndex": {
     *                        "MAIN": 0,
     *                        ...
     *                    },
     *
     *     "indexToName": {
     *                        0: "MAIN",
     *                        ...
     *                    }
     * }
     * </pre>
     *
     * @return tabs info as JSON
     */
    public String getTabsInfo() {
        Map<String, Integer> nameToIndex = new HashMap<>();
        Map<Integer, String> indexToName = new HashMap<>();

        for (Tab tab : Tab.values()) {
            nameToIndex.put(tab.name(), tab.getIndex());
            indexToName.put(tab.getIndex(), tab.name());
        }

        Map<String, Map> tabsInfo = new HashMap<>();
        tabsInfo.put("nameToIndex", nameToIndex);
        tabsInfo.put("indexToName", indexToName);

        return new JSONObject(tabsInfo).toString();
    }

    public Product getProduct() {
        return product;
    }

    public List<ProductType> getAvailableProductTypes() {
        return productTypeService.getAll().getAll();
    }

    public IdentifiableConverter<ProductType> getProductTypesConverter() {
        return new IdentifiableConverter<>(productTypeService.getAll().getAll());
    }

    public List<ProductStatus> getAvailableStatuses() {
        return Arrays.asList(ProductStatus.values());
    }

    public List<Size> getAvailableSizes() {
        return sizeService.getAll().getAll();
    }

    public IdentifiableConverter<Size> getSizesConverter() {
        return new IdentifiableConverter<>(sizeService.getAll().getAll(), true);
    }

    public List<ProductLabel> getAvailableLabels() {
        return productLabelService.getAll().getAll();
    }

    public IdentifiableConverter<ProductLabel> getLabelConverter() {
        return new IdentifiableConverter<>(productLabelService.getAll().getAll(), true);
    }

    public List<Category> getSortedProductCategories() {
        final IdentifiableList<Category> allCategories = categoryService.getAll();

opresent-cms/src/main/java/ru/opresent/web/cms/bean/product/ProductFilterBean.java
package ru.opresent.web.cms.bean.product;

import org.springframework.stereotype.Component;
import ru.opresent.core.domain.*;
import ru.opresent.core.service.api.CategoryService;
import ru.opresent.core.service.api.ProductTypeService;
import ru.opresent.core.service.api.SizeService;
import ru.opresent.web.cms.component.table.FilterActionListener;
import ru.opresent.web.cms.converter.IdentifiableConverter;

import javax.annotation.Resource;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * User: artem
 * Date: 22.04.14
 * Time: 0:03
 */
@Component("productFilterBean")
//@Scope("session")
public class ProductFilterBean implements Serializable {

    @Resource(name = "productTypeService")
    private ProductTypeService productTypeService;

    @Resource(name = "sizeService")
    private SizeService sizeService;

    @Resource(name = "categoryService")
    private CategoryService categoryService;

    private DefaultProductFilter filter = new DefaultProductFilter();

    private FilterActionListener filterActionListener;

    public void invokeFiltering() {
        filterActionListener.filteringInvoked();
    }

    public void invokeReset() {
        filter = new DefaultProductFilter();
        filterActionListener.resetInvoked();
    }

    // setters & getters

    public DefaultProductFilter getFilter() {
        return filter;
    }

    public void setFilterActionListener(FilterActionListener filterActionListener) {
        this.filterActionListener = filterActionListener;
    }

    public List<Category> getCategories() {
        return categoryService.getAll().getAll();
    }

    public IdentifiableConverter<Category> getCategoryConverter() {
        return new IdentifiableConverter<>(getCategories(), true);
    }

    public List<Size> getSizes() {
        return sizeService.getAll().getAll();
    }

    public IdentifiableConverter<Size> getSizeConverter() {
        return new IdentifiableConverter<>(getSizes(), true);
    }

    public List<ProductType> getProductTypes() {
        return productTypeService.getAll().getAll();
    }

    public IdentifiableConverter<ProductType> getProductTypeConverter() {
        return new IdentifiableConverter<>(getProductTypes(), true);
    }

    public List<ProductStatus> getStatuses() {
        return Arrays.asList(ProductStatus.values());
    }

}

opresent-cms/src/main/webapp/pages/product_type/product_type.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xml:lang="en" lang="en">

    <ui:define name="windowTitle">
        <f:loadBundle var="product_type" basename="ru.opresent.web.cms.i18n.product_type.product_type"/>
        <h:outputText value="#{productTypeBean.addition ? product_type.add_title : product_type.edit_title}"/>
    </ui:define>

    <ui:define name="content">
        <f:loadBundle var="common" basename="ru.opresent.web.cms.i18n.common"/>
        <f:loadBundle var="buttons" basename="ru.opresent.web.cms.i18n.buttons"/>

        <style type="text/css">
            .productTypeFieldDesc {
                text-align: right;
                padding-right: 10px;
                padding-bottom: 10px;
            }

            .productTypeField {
                text-align: left !important;
                padding-bottom: 10px;
            }

            .productTypeField .ui-inputfield,
            .productTypeField .ui-inputtextarea {
                width: 300px;
            }

            .productTypeField img {
                max-width: 200px;
            }

            .productTypeButtons button {
                margin-top: 20px;
                margin-right: 20px;
            }
        </style>

        <p:panel header="#{productTypeBean.addition ? product_type.add_title : product_type.edit_title}"
                 collapsed="true" styleClass="pageHeaderPanel"/>

        <h:form id="productTypeForm">
            <h:panelGrid columns="2" columnClasses="productTypeFieldDesc,productTypeField">
                <p:outputLabel for="productTypeName" value="#{product_type.name}"/>
                <p:inputText id="productTypeName" value="#{productTypeBean.productType.name}"
                             maxlength="#{entitiesConstraints.productTypeNameMaxLength}"/>

                <p:outputLabel for="productTypeEntityName" value="#{product_type.entity_name}"/>
                <p:inputText id="productTypeEntityName" value="#{productTypeBean.productType.entityName}"
                             maxlength="#{entitiesConstraints.entityNameMaxLength}"/>

                <p:outputLabel for="livemasterAliasesInput" value="#{product_type.livemaster_aliases}"/>
                <p:autoComplete id="livemasterAliasesInput" value="#{productTypeBean.livemasterAliases}"
                                var="livemasterAlias" itemLabel="#{livemasterAlias}" itemValue="#{livemasterAlias}"
                                completeMethod="#{productTypeBean.completeAlias}" multiple="true"
                                scrollHeight="100">
                    <p:ajax event="itemUnselect" listener="#{productTypeBean.onAliasUnselect}"
                            update="@this"/>

                    <p:column>
                        <h:outputText value="#{livemasterAlias}" />
                    </p:column>
                </p:autoComplete>

                <h:outputText value="#{product_type.image}"/>
                <h:panelGroup id="productTypeImage">
                    <p:fileUpload id="productTypeImageUpload" styleClass="productTypeImageUpload"
                                  allowTypes="#{imageFileBean.allowTypesPattern}"
                                  invalidFileMessage="#{imageFileBean.invalidFileMessage}"
                                  sizeLimit="#{imageFileBean.sizeLimit}"
                                  invalidSizeMessage="#{imageFileBean.invalidSizeMessage}"
                                  multiple="false"
                                  fileUploadListener="#{productTypeBean.handleProductTypeImageUpload}"
                                  auto="true" label="#{buttons.define}"
                                  update="productTypeImage"
                                  style="width: 310px;text-align: center;"/>

                    <h:outputText value="#{product_type.image_not_defined}" styleClass="alarm"
                                  rendered="#{empty productTypeBean.productType.image}"/>

                    <h:panelGroup rendered="#{not empty productTypeBean.productType.image}">
                        <img src="#{imageFileManager.createUrl(productTypeBean.productType.image)}"/>
                    </h:panelGroup>
                </h:panelGroup>

                <p:outputLabel for="productTypeDesc" value="#{product_type.description}"/>
                <h:panelGroup>
                    <p:inputTextarea id="productTypeDesc" value="#{productTypeBean.productType.description}"
                                     cols="50" rows="6" maxlength="#{entitiesConstraints.productTypeDescriptionMaxLength}"
                                     counter="productTypeDescCounter" counterTemplate="#{common.chars_remaining}"/>
                    <h:outputText id="productTypeDescCounter" styleClass="charsCounter"/>
                </h:panelGroup>
            </h:panelGrid>

            <h:panelGroup styleClass="productTypeButtons">
                <p:commandButton id="saveButton" value="#{buttons.save}" icon="ui-icon-disk"
                                 process="@this productTypeName productTypeEntityName livemasterAliasesInput productTypeDesc"
                                 action="#{productTypeBean.save}" update=":messages"/>

                <p:button id="returnToListButton" value="#{buttons.return_to_list}" icon="ui-icon-arrowthick-1-w"
                          outcome="product_type_list?faces-redirect=true"/>
            </h:panelGroup>

        </h:form>
    </ui:define>

</ui:composition>

opresent-cms/src/main/webapp/pages/product_type/product_type_list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xml:lang="en" lang="en">

    <ui:define name="windowTitle">
        <f:loadBundle var="product_type_list" basename="ru.opresent.web.cms.i18n.product_type.product_type_list"/>
        <h:outputText value="#{product_type_list.title}"/>
    </ui:define>

    <ui:define name="content">
        <f:loadBundle var="common" basename="ru.opresent.web.cms.i18n.common"/>
        <f:loadBundle var="buttons" basename="ru.opresent.web.cms.i18n.buttons"/>

        <style type="text/css">
            .moveButton {
                width: 35px;
                height: 35px;
                float: left;
            }
        </style>

        <p:panel header="#{product_type_list.title}" collapsed="true" styleClass="pageHeaderPanel"/>

        <h:form id="listForm">
            <p:dataTable id="productTypesTable" value="#{productTypeListBean.productTypes}"
                         var="productType" rowKey="#{productType.id}"
                         selection="#{productTypeListBean.selectedProductType}" selectionMode="single">

                <f:facet name="header">
                    <h:panelGroup id="tableButtons">
                        <p:commandButton id="addButton" value="#{buttons.add}" icon="ui-icon-plus"
                                         ajax="false" action="#{productTypeListBean.add}"/>

                        <p:commandButton id="editButton" value="#{buttons.edit}" icon="ui-icon-pencil"
                                         ajax="false" action="#{productTypeListBean.edit}"
                                         rendered="#{not empty productTypeListBean.selectedProductType}"/>

                        <p:commandButton id="deleteButton" value="#{buttons.delete}" type="button" onclick="PF('deleteConfirmVar').show();"
                                         icon="ui-icon-close"
                                         rendered="#{not empty productTypeListBean.selectedProductType}"/>

                        <p:confirmDialog message="#{messageFormatBean.format(
                                                              product_type_list.delete_confirm_msg,
                                                              productTypeListBean.selectedProductType.name)}"
                                         header="#{messageFormatBean.format(
                                                                 product_type_list.delete_confirm_header,
                                                                 productTypeListBean.selectedProductType.name)}"
                                         widgetVar="deleteConfirmVar" closeOnEscape="true">

                            <p:commandButton value="#{buttons.yes}" icon="ui-icon-check"
                                             process="@this" action="#{productTypeListBean.delete}"
                                             update=":messages @form" oncomplete="PF('deleteConfirmVar').hide();"/>

                            <p:commandButton value="#{buttons.no}" icon="ui-icon-close" type="button" onclick="PF('deleteConfirmVar').hide();"/>
                        </p:confirmDialog>
                    </h:panelGroup>
                </f:facet>

                <p:ajax event="rowSelect" update="tableButtons"/>
                <p:ajax event="rowUnselect" update="tableButtons"/>

                <p:column headerText="Id" width="20">
                    <h:outputText value="#{productType.id}"/>
                </p:column>

                <p:column headerText="#{product_type_list.image}"
                          width="#{imageFileManager.getSizeOption('PRODUCT_TYPE_IMAGE_IN_WELCOME').size.width}">
                    <img src="#{imageFileManager.createUrl(productType.image, 'PRODUCT_TYPE_IMAGE_IN_WELCOME')}"/>
                </p:column>

                <p:column headerText="#{product_type_list.name}">
                    <h:outputText value="#{productType.name}"/>
                </p:column>

                <p:column headerText="#{product_type_list.entity_name}">
                    <h:outputText value="#{productType.entityName}"/>
                </p:column>

                <p:column headerText="#{product_type_list.livemaster_aliases}" styleClass="left">
                    <ul>
                        <ui:repeat value="#{productTypeListBean.getLivemasterAliases(productType)}" var="alias">
                            <li><h:outputText value="#{alias}"/></li>
                        </ui:repeat>
                    </ul>
                </p:column>

                <p:column headerText="#{product_type_list.description}">
                    <h:outputText value="#{productType.description}"/>
                </p:column>

                <p:column headerText="#{product_type_list.change_position}">
                    <div style="margin-left: 30px; margin-right: 30px;">
                        <div class="moveButton">
                            <p:commandButton id="moveUp" action="#{productTypeListBean.moveUp(productType)}"
                                             process="@this"
                                             update="@form :messages"
                                             icon="ui-icon-arrowthick-1-n"
                                             rendered="#{orderedEntityServiceHelper.canMoveUp(productType)}"/>
                        </div>

                        <div class="moveButton">
                            <p:commandButton id="moveDown" action="#{productTypeListBean.moveDown(productType)}"
                                             process="@this"
                                             update="@form :messages"
                                             icon="ui-icon-arrowthick-1-s"
                                             rendered="#{orderedEntityServiceHelper.canMoveDown(productType, productTypeListBean.productTypes)}"/>
                        </div>
                    </div>
                </p:column>

            </p:dataTable>
        </h:form>
    </ui:define>

</ui:composition>