opresent-cms/src/main/java/ru/opresent/web/cms/bean/ImageFileBean.java
package ru.opresent.web.cms.bean;

import org.primefaces.model.UploadedFile;
import org.springframework.stereotype.Component;
import ru.opresent.core.component.api.image.ImageConstraints;
import ru.opresent.core.domain.image.HasCopyrightOption;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.service.api.ImageService;
import ru.opresent.web.cms.converter.UploadedFileToImageConverter;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.Resource;
import java.util.List;

/**
 * User: artem
 * Date: 31.03.14
 * Time: 0:32
 */
@Component("imageFileBean")
public class ImageFileBean {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.image_file";

    @Resource(name = "imageConstraints")
    private ImageConstraints imageConstraints;

    @Resource(name = "imageService")
    private ImageService imageService;

    @Resource(name = "uploadedFileToImageConverter")
    private UploadedFileToImageConverter uploadedFileToImageConverter;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    public String getAllowTypesPattern() {
        StringBuilder pattern = new StringBuilder("/(\\.|\\/)(");

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                pattern.append("|");
            }
            pattern.append(formats.get(i));
        }

        pattern.append(")$/");
        return pattern.toString();
    }

    public String getInvalidFileMessage() {
        StringBuilder formatsStr = new StringBuilder();

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                formatsStr.append(", ");
            }
            formatsStr.append(formats.get(i));
        }

        return messageManager.getMessage(BUNDLE_NAME, "invalid_file_client_msg", formatsStr.toString());
    }

    /**
     * @return size limit in bytes
     */
    public int getSizeLimit() {
        return imageConstraints.getMaxSize();
    }

    public String getInvalidSizeMessage() {
        int maxSize = imageConstraints.getMaxSize();
        return messageManager.getMessage(BUNDLE_NAME, "invalid_size_client_msg", maxSize / 1024, maxSize / 1024 / 1024);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse) {
        return saveImage(uploadedFile, imageUse, HasCopyrightOption.INHERIT_FROM_IMAGE_USE);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse, HasCopyrightOption hasCopyrightOption) {
        Image image = uploadedFileToImageConverter.convert(uploadedFile, imageUse, hasCopyrightOption);
        return imageService.save(image);
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/section/SectionBean.java
package ru.opresent.web.cms.bean.section;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.domain.section.Section;
import ru.opresent.core.domain.section.SectionItem;
import ru.opresent.core.domain.section.SectionType;
import ru.opresent.core.service.ServiceException;
import ru.opresent.core.service.api.SectionService;
import ru.opresent.web.cms.component.rich_text.RichTextContainer;
import ru.opresent.web.cms.util.MessageManager;
import ru.opresent.web.cms.util.WebUtils;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.context.FacesContext;
import javax.validation.ConstraintViolationException;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * User: artem
 * Date: 07.06.14
 * Time: 21:35
 */
@Component("sectionBean")
@Scope("view")
public class SectionBean implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.section.section";

    @Resource(name = "sectionService")
    private transient SectionService sectionService;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    private Mode mode;
    private SectionType sectionType;
    private Section section;
    private List<SectionItem> sectionItems;
    private SectionItem selectedSectionItem;

    @PostConstruct
    private void init() {
        Long sectionId = WebUtils.getLongRequestParameter("id");
        mode = sectionId == null ? Mode.ADD : Mode.EDIT;

        if (mode == Mode.EDIT) {
            section = sectionService.load(sectionId);
            sectionType = section.getType();
            if (sectionType == SectionType.LIST) {
                sectionItems = sectionService.loadItems(sectionId);
            }
        }
    }

    public void sectionTypeChanged() {
        if (isEditing()) {
            throw new IllegalStateException("Section type cannot be changed in editing mode!");
        }

        if (sectionType == null) {
            throw new IllegalStateException("Section type cannot be changed to null!");
        }

        Section previousSection = section;
        section = new Section(sectionType);

        if (previousSection != null) {
            section.setName(previousSection.getName());
            section.setEntityName(previousSection.getEntityName());
            section.setVisible(previousSection.isVisible());
        }
    }

    public String save() {
        long sectionId;
        try {
            sectionId = sectionService.save(section);
        } catch (ConstraintViolationException e) {
            messageManager.addErrorMessage(e);
            return null;
        }

        messageManager.addInfoMessage(BUNDLE_NAME, "save_success", section.getName());
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);

        return "section?faces-redirect=true&id=" + sectionId;
    }

    public String addSectionItem() {
        return "section_item?faces-redirect=true&section_id=" + section.getId();
    }

    public String editSectionItem() {
        return "section_item?faces-redirect=true&id=" + selectedSectionItem.getId();
    }

    public String deleteSectionItem() {
        try {
            sectionService.deleteSectionItem(selectedSectionItem.getId());
        } catch (ServiceException e) {
            messageManager.addErrorMessage(e);
            return null;
        }

        messageManager.addInfoMessage(BUNDLE_NAME, "delete_item_success", selectedSectionItem.getName());
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);

        return "section?faces-redirect=true&id=" + section.getId();
    }

    public String moveUpSectionItem(SectionItem sectionItem) {
        sectionService.moveUp(sectionItem);
        return "section?faces-redirect=true&id=" + section.getId();
    }

    public String moveDownSectionItem(SectionItem sectionItem) {
        sectionService.moveDown(sectionItem);
        return "section?faces-redirect=true&id=" + section.getId();
    }

    // setters & getters (BEGIN)

    public boolean isAddition() {
        return mode == Mode.ADD;
    }

    public boolean isEditing() {
        return mode == Mode.EDIT;
    }

    public SectionType getSectionType() {
        return sectionType;
    }

    public void setSectionType(SectionType sectionType) {
        this.sectionType = sectionType;
    }

    public List<SectionType> getAvailableTypes() {
        return Arrays.asList(SectionType.values());
    }

    public Section getSection() {
        return section;
    }

    public List<SectionItem> getSectionItems() {
        if (section.getType() != SectionType.LIST) {
            throw new IllegalStateException("Section items exists only for section type: " + SectionType.LIST +
                    ", but current is: " + section.getType());
        }
        return sectionItems;
    }

    public SectionItem getSelectedSectionItem() {
        return selectedSectionItem;
    }

    public void setSelectedSectionItem(SectionItem selectedSectionItem) {
        this.selectedSectionItem = selectedSectionItem;
    }

    public RichTextContainer getSectionTextContainer() {
        return new RichTextContainer() {
            @Override
            public String getText() {
                return section.getText();
            }

            @Override
            public void setText(String text) {
                section.setText(text);
            }
        };
    }

    // setters & getters (END)

    public enum Mode {
        ADD, EDIT
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/section/SectionItemBean.java
package ru.opresent.web.cms.bean.section;

import org.primefaces.event.FileUploadEvent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.domain.section.SectionItem;
import ru.opresent.core.service.api.SectionService;
import ru.opresent.web.cms.bean.ImageFileBean;
import ru.opresent.web.cms.component.rich_text.RichTextContainer;
import ru.opresent.web.cms.util.MessageManager;
import ru.opresent.web.cms.util.WebUtils;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.context.FacesContext;
import javax.validation.ConstraintViolationException;
import java.io.Serializable;

/**
 * User: artem
 * Date: 07.06.14
 * Time: 21:35
 */
@Component("sectionItemBean")
@Scope("view")
public class SectionItemBean implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.section.section_item";

    @Resource(name = "sectionService")
    private transient SectionService sectionService;

    @Resource(name = "imageFileBean")
    private transient ImageFileBean imageFileBean;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    private Mode mode;
    private SectionItem sectionItem;

    @PostConstruct
    private void init() {
        Long sectionId = WebUtils.getLongRequestParameter("section_id");
        Long sectionItemId = WebUtils.getLongRequestParameter("id");

        if (sectionId == null && sectionItemId == null) {
            throw new IllegalArgumentException("Section id or section item id must be defined as request parameter!");
        }
        if (sectionId != null && sectionItemId != null) {
            throw new IllegalArgumentException("Section id and section item id not be defined together as request parameters!");
        }

        if (sectionId != null) {
            mode = Mode.ADD;
            sectionItem = new SectionItem();
            sectionItem.setSection(sectionService.getAll().getById(sectionId));
        }

        if (sectionItemId != null) {
            mode = Mode.EDIT;
            sectionItem = sectionService.loadItem(sectionItemId);
        }
    }

    public void handleSectionItemImageUpload(FileUploadEvent event) {
        Image image = imageFileBean.saveImage(event.getFile(), ImageUse.SECTION_ITEM_PREVIEW_IMAGE);
        sectionItem.setPreview(image);
    }

    public String save() {
        try {
            sectionItem = sectionService.save(sectionItem);
        } catch (ConstraintViolationException e) {
            messageManager.addErrorMessage(e);
            return null;
        }

        messageManager.addInfoMessage(BUNDLE_NAME, "save_success", sectionItem.getName());
        FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);

        return "section_item?faces-redirect=true&id=" + sectionItem.getId();
    }

    // setters & getters (BEGIN)

    public boolean isAddition() {
        return mode == Mode.ADD;
    }

    public boolean isEditing() {
        return mode == Mode.EDIT;
    }

    public SectionItem getSectionItem() {
        return sectionItem;
    }

    public RichTextContainer getShortTextContainer() {
        return new RichTextContainer() {
            @Override
            public String getText() {
                return sectionItem.getShortText();
            }

            @Override
            public void setText(String text) {
                sectionItem.setShortText(text);
            }
        };
    }

    public RichTextContainer getFullTextContainer() {
        return new RichTextContainer() {
            @Override
            public String getText() {
                return sectionItem.getFullText();
            }

            @Override
            public void setText(String text) {
                sectionItem.setFullText(text);
            }
        };
    }

    // setters & getters (END)

    public enum Mode {
        ADD, EDIT
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/section/SectionListBean.java
package ru.opresent.web.cms.bean.section;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.domain.section.Section;
import ru.opresent.core.service.api.SectionService;
import ru.opresent.web.cms.Deleter;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.Resource;
import java.io.Serializable;
import java.util.List;

/**
 * User: artem
 * Date: 07.06.14
 * Time: 21:36
 */
@Component("sectionListBean")
@Scope("view")
public class SectionListBean implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.section.section_list";

    @Resource(name = "sectionService")
    private transient SectionService sectionService;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    private Section selectedSection;

    public String edit() {
        return "section?faces-redirect=true&id=" + selectedSection.getId();
    }

    public void moveUp(Section section) {
        sectionService.moveUp(section);
    }

    public void moveDown(Section section) {
        sectionService.moveDown(section);
    }

    // setters & getters

    public Deleter getDeleter() {
        return new Deleter() {
            @Override
            public void delete() {
                sectionService.deleteSection(selectedSection.getId());
                messageManager.addInfoMessage(BUNDLE_NAME, "delete_success", selectedSection.getName());
                selectedSection = null;
            }
        };
    }

    public Section getSelectedSection() {
        return selectedSection;
    }

    public void setSelectedSection(Section selectedSection) {
        this.selectedSection = selectedSection;
    }

    public List<Section> getSections() {
        return sectionService.getAll().getAll();
    }
}

opresent-cms/src/main/webapp/pages/section/section.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:opresent="http://java.sun.com/jsf/composite/opresent"
                xmlns:pe="http://primefaces.org/ui/extensions"
                xml:lang="en" lang="en">

    <ui:define name="windowTitle">
        <f:loadBundle var="section_bundle" basename="ru.opresent.web.cms.i18n.section.section"/>
        <f:loadBundle var="section_item_bundle" basename="ru.opresent.web.cms.i18n.section.section_item"/>

        <h:outputText value="#{sectionBean.addition ?
                               section_bundle.title_addition :
                               messageFormatBean.format(section_bundle.title_editing, sectionBean.section.id)}"/>
    </ui:define>

    <ui:define name="content">
        <f:loadBundle var="buttons" basename="ru.opresent.web.cms.i18n.buttons"/>

        <h:form id="sectionForm">

            <p:panel header="#{sectionBean.addition ?
                                   section_bundle.title_addition :
                                   messageFormatBean.format(section_bundle.title_editing, sectionBean.section.id)}"
                     collapsed="true" styleClass="pageHeaderPanel"/>

            <h:panelGrid columns="2">
                <h:outputText value="#{section_bundle.type}"/>
                <p:selectOneMenu value="#{sectionBean.sectionType}" disabled="#{sectionBean.editing}"
                                 required="true" requiredMessage="#{section_bundle.type_not_defined}"
                                 style="width: 150px;">

                    <p:ajax event="change" process="@form"
                            update="@(.richTextEditorPanel, .bottomButtons, .typeDependencyContainer)"
                            listener="#{sectionBean.sectionTypeChanged}"/>

                    <f:selectItem itemLabel="#{section_bundle.define_type}"
                                  noSelectionOption="true" itemDisabled="true"/>
                    <f:selectItems value="#{sectionBean.availableTypes}" var="type"
                                   itemValue="#{type}" itemLabel="#{enumHelper.getDescription(type)}"/>
                </p:selectOneMenu>

                <h:panelGroup id="sectionNameFieldDesc" styleClass="typeDependencyContainer">
                    <h:outputText value="#{section_bundle.name}"
                                  rendered="#{not empty sectionBean.section}"/>
                </h:panelGroup>
                <h:panelGroup id="sectionNameField" styleClass="typeDependencyContainer">
                    <p:inputText value="#{sectionBean.section.name}"
                                 styleClass="processedSectionField"
                                 maxlength="#{entitiesConstraints.sectionNameMaxLength}"
                                 rendered="#{not empty sectionBean.section}"/>
                </h:panelGroup>

                <h:panelGroup id="sectionEntityNameFieldDesc" styleClass="typeDependencyContainer">
                    <h:outputText value="#{section_bundle.entity_name}"
                                  rendered="#{not empty sectionBean.section}"/>
                </h:panelGroup>
                <h:panelGroup id="sectionEntityNameField" styleClass="typeDependencyContainer">
                    <p:inputText id="sectionEntityName"
                                 value="#{sectionBean.section.entityName}"
                                 styleClass="processedSectionField"
                                 maxlength="#{entitiesConstraints.entityNameMaxLength}"
                                 rendered="#{not empty sectionBean.section}"/>
                    <pe:keyFilter for="sectionEntityName" regEx="/#{entitiesConstraints.entityNameRegexp}/"/>
                </h:panelGroup>

                <h:panelGroup id="sectionVisibleFieldDesc" styleClass="typeDependencyContainer">
                    <h:outputText value="#{section_bundle.visible}"
                                  rendered="#{not empty sectionBean.section}"/>
                </h:panelGroup>
                <h:panelGroup id="sectionVisibleField" styleClass="typeDependencyContainer">
                    <p:selectBooleanCheckbox value="#{sectionBean.section.visible}"
                                             styleClass="processedSectionField"
                                             rendered="#{not empty sectionBean.section}"/>
                </h:panelGroup>
            </h:panelGrid>

            <h:panelGroup id="richTextEditorPanel" styleClass="richTextEditorPanel">
                <opresent:richTextEditor id="sectionTextEditor"
                                    container="#{sectionBean.sectionTextContainer}"
                                    rendered="#{not empty sectionBean.section}"/>
            </h:panelGroup>

            <h:panelGroup id="bottomButtons" styleClass="bottomButtons">
                <p:commandButton id="saveButton"
                                 rendered="#{not empty sectionBean.section}"
                                 process="@this @(.processedSectionField) sectionTextEditor:ckEditor"
                                 action="#{sectionBean.save}"
                                 update=":messages"
                                 value="#{buttons.save}" icon="ui-icon-disk"/>

                <p:button id="returnToListButton" value="#{buttons.return_to_list}" icon="ui-icon-arrowthick-1-w"
                          style="margin-top: 20px;"
                          outcome="section_list?faces-redirect=true"/>
            </h:panelGroup>

            <h:panelGroup rendered="#{sectionBean.editing and sectionBean.section.type eq 'LIST'}">

                <h:panelGroup id="tableButtons" style="display: block; text-align: left; margin-top: 30px;">
                    <p:commandButton id="addButton" value="#{buttons.add}" icon="ui-icon-plus"
                                     action="#{sectionBean.addSectionItem}" process="@this"/>

                    <p:commandButton id="editButton" value="#{buttons.edit}" icon="ui-icon-pencil"
                                     action="#{sectionBean.editSectionItem}" process="@this"
                                     rendered="#{not empty sectionBean.selectedSectionItem}"/>

                    <p:commandButton id="deleteButton" value="#{buttons.delete}" type="button" onclick="PF('deleteSectionItemConfirmVar').show();"
                                     icon="ui-icon-close"
                                     rendered="#{not empty sectionBean.selectedSectionItem}"/>

                    <p:confirmDialog message="#{messageFormatBean.format(section_item_bundle.delete_dialog_msg,
                                                                                 sectionBean.selectedSectionItem.name)}"
                                     header="#{section_item_bundle.delete_dialog_title}"
                                     widgetVar="deleteSectionItemConfirmVar" closeOnEscape="true">

                        <p:commandButton value="#{buttons.yes}" icon="ui-icon-check"
                                         process="@this" action="#{sectionBean.deleteSectionItem}"/>

                        <p:commandButton value="#{buttons.no}" icon="ui-icon-close" type="button" onclick="PF('deleteSectionItemConfirmVar').hide();"/>
                    </p:confirmDialog>
                </h:panelGroup>

                <p:dataTable value="#{sectionBean.sectionItems}" var="item" rowKey="#{item.id}"
                             selectionMode="single" selection="#{sectionBean.selectedSectionItem}">

                    <p:ajax event="rowSelect" update=":sectionForm:tableButtons"/>
                    <p:ajax event="rowUnselect" update=":sectionForm:tableButtons"/>

                    <p:column headerText="Id" width="20">
                        <h:outputText value="#{item.id}"/>
                    </p:column>

                    <p:column headerText="#{section_item_bundle.preview}"
                              width="#{imageFileManager.getSizeOption('SECTION_ITEM_PREVIEW_IN_SECTION_LIST').size.width}">
                        <img src="#{imageFileManager.createUrl(item.preview, 'SECTION_ITEM_PREVIEW_IN_SECTION_LIST')}"/>
                    </p:column>

                    <p:column headerText="#{section_item_bundle.name}">
                        <h:outputText value="#{item.name}"/>
                    </p:column>

                    <p:column headerText="#{section_item_bundle.short_text}">
                        <h:outputText value="#{item.shortText}"/>
                    </p:column>

                    <p:column headerText="#{section_bundle.visible}" width="100">
                        <p:selectBooleanCheckbox value="#{item.visible}" disabled="true"/>
                    </p:column>

                    <p:column headerText="#{section_bundle.change_position}">
                        <div style="margin-left: 30px; margin-right: 30px;">
                            <div class="moveButton">
                                <p:commandButton id="moveUp" action="#{sectionBean.moveUpSectionItem(item)}"
                                                 ajax="false"
                                                 icon="ui-icon-arrowthick-1-n"
                                                 rendered="#{orderedEntityServiceHelper.canMoveUp(item)}"/>
                            </div>

                            <div class="moveButton">
                                <p:commandButton id="moveDown" action="#{sectionBean.moveDownSectionItem(item)}"
                                                 ajax="false"
                                                 icon="ui-icon-arrowthick-1-s"
                                                 rendered="#{orderedEntityServiceHelper.canMoveDown(item, sectionBean.sectionItems)}"/>
                            </div>
                        </div>
                    </p:column>

                </p:dataTable>

            </h:panelGroup>
        </h:form>

    </ui:define>

</ui:composition>

opresent-cms/src/main/webapp/pages/section/section_item.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:opresent="http://java.sun.com/jsf/composite/opresent"
                xml:lang="en" lang="en">

    <ui:define name="windowTitle">
        <f:loadBundle var="section_item_bundle" basename="ru.opresent.web.cms.i18n.section.section_item"/>

        <h:outputText value="#{sectionItemBean.addition ?
                               section_item_bundle.title_addition :
                               messageFormatBean.format(section_item_bundle.title_editing, sectionItemBean.sectionItem.id)}"/>
    </ui:define>

    <ui:define name="content">

        <style type="text/css">
            .sectionItemFieldDesc {
                text-align: right;
                padding-right: 10px;
                padding-bottom: 10px;
            }

            .sectionItemField .ui-inputfield {
                width: 300px;
            }

            .sectionItemField {
                text-align: left !important;
                padding-bottom: 10px;
            }
        </style>

        <f:loadBundle var="buttons" basename="ru.opresent.web.cms.i18n.buttons"/>
        <f:loadBundle var="common" basename="ru.opresent.web.cms.i18n.common"/>

        <h:form id="sectionItemForm">

            <p:panel header="#{sectionItemBean.addition ?
                                   section_item_bundle.title_addition :
                                   messageFormatBean.format(section_item_bundle.title_editing, sectionItemBean.sectionItem.id)}"
                     collapsed="true" styleClass="pageHeaderPanel"/>

            <h:panelGrid columns="2" columnClasses="sectionItemFieldDesc,sectionItemField">
                <h:outputText value="#{section_item_bundle.section}"/>
                <p:inputText value="#{sectionItemBean.sectionItem.section.name}" disabled="true"/>

                <h:outputText value="#{section_item_bundle.name}"/>
                <p:inputText value="#{sectionItemBean.sectionItem.name}"
                             styleClass="processedSectionItemField"
                             maxlength="#{entitiesConstraints.sectionItemNameMaxLength}"/>

                <h:outputText value="#{section_item_bundle.visible}"/>
                <p:selectBooleanCheckbox value="#{sectionItemBean.sectionItem.visible}"
                                         styleClass="processedSectionItemField"/>

                <h:outputText value="#{section_item_bundle.preview}"/>
                <h:panelGroup id="sectionItemPreview">
                    <p:fileUpload id="sectionItemImageUpload" styleClass="sectionItemImageUpload"
                                  allowTypes="#{imageFileBean.allowTypesPattern}"
                                  invalidFileMessage="#{imageFileBean.invalidFileMessage}"
                                  sizeLimit="#{imageFileBean.sizeLimit}"
                                  invalidSizeMessage="#{imageFileBean.invalidSizeMessage}"
                                  multiple="false"
                                  fileUploadListener="#{sectionItemBean.handleSectionItemImageUpload}"
                                  auto="true" label="#{buttons.define}"
                                  update="sectionItemPreview"
                                  style="width: 310px;text-align: center;"/>

                    <h:outputText value="#{section_item_bundle.preview_not_defined}" styleClass="alarm"
                                  rendered="#{empty sectionItemBean.sectionItem.preview}"/>

                    <h:panelGroup rendered="#{not empty sectionItemBean.sectionItem.preview}">
                        <img src="#{imageFileManager.createUrl(sectionItemBean.sectionItem.preview, 'SECTION_ITEM_PREVIEW_IN_SECTION_LIST')}"/>
                    </h:panelGroup>
                </h:panelGroup>

                <h:outputText value="#{section_item_bundle.short_text}"/>
                <opresent:richTextEditor id="sectionItemShortTextEditor"
                                    container="#{sectionItemBean.shortTextContainer}"
                                    editorHeight="200"/>

                <h:outputText value="#{section_item_bundle.full_text}"/>
                <opresent:richTextEditor id="sectionItemFullTextEditor"
                                    container="#{sectionItemBean.fullTextContainer}"/>
            </h:panelGrid>

            <h:panelGroup id="bottomButtons" styleClass="bottomButtons">
                <p:commandButton id="saveButton"
                                 process="@this @(.processedSectionItemField)
                                          sectionItemShortTextEditor:ckEditor
                                          sectionItemFullTextEditor:ckEditor"
                                 action="#{sectionItemBean.save}"
                                 update=":messages"
                                 value="#{buttons.save}" icon="ui-icon-disk"/>

                <p:button id="returnToListButton" value="#{buttons.return_to_list}" icon="ui-icon-arrowthick-1-w"
                          style="margin-top: 20px;"
                          outcome="section?faces-redirect=true&amp;id=#{sectionItemBean.sectionItem.section.id}"/>
            </h:panelGroup>

        </h:form>

    </ui:define>

</ui:composition>