opresent-cms/src/main/java/ru/opresent/web/cms/bean/ImageFileBean.java
package ru.opresent.web.cms.bean;

import org.primefaces.model.UploadedFile;
import org.springframework.stereotype.Component;
import ru.opresent.core.component.api.image.ImageConstraints;
import ru.opresent.core.domain.image.HasCopyrightOption;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.service.api.ImageService;
import ru.opresent.web.cms.converter.UploadedFileToImageConverter;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.Resource;
import java.util.List;

/**
 * User: artem
 * Date: 31.03.14
 * Time: 0:32
 */
@Component("imageFileBean")
public class ImageFileBean {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.image_file";

    @Resource(name = "imageConstraints")
    private ImageConstraints imageConstraints;

    @Resource(name = "imageService")
    private ImageService imageService;

    @Resource(name = "uploadedFileToImageConverter")
    private UploadedFileToImageConverter uploadedFileToImageConverter;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    public String getAllowTypesPattern() {
        StringBuilder pattern = new StringBuilder("/(\\.|\\/)(");

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                pattern.append("|");
            }
            pattern.append(formats.get(i));
        }

        pattern.append(")$/");
        return pattern.toString();
    }

    public String getInvalidFileMessage() {
        StringBuilder formatsStr = new StringBuilder();

        List<String> formats = imageConstraints.getSupportedFormats();
        for (int i = 0; i < formats.size(); i++) {
            if (i != 0) {
                formatsStr.append(", ");
            }
            formatsStr.append(formats.get(i));
        }

        return messageManager.getMessage(BUNDLE_NAME, "invalid_file_client_msg", formatsStr.toString());
    }

    /**
     * @return size limit in bytes
     */
    public int getSizeLimit() {
        return imageConstraints.getMaxSize();
    }

    public String getInvalidSizeMessage() {
        int maxSize = imageConstraints.getMaxSize();
        return messageManager.getMessage(BUNDLE_NAME, "invalid_size_client_msg", maxSize / 1024, maxSize / 1024 / 1024);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse) {
        return saveImage(uploadedFile, imageUse, HasCopyrightOption.INHERIT_FROM_IMAGE_USE);
    }

    public Image saveImage(UploadedFile uploadedFile, ImageUse imageUse, HasCopyrightOption hasCopyrightOption) {
        Image image = uploadedFileToImageConverter.convert(uploadedFile, imageUse, hasCopyrightOption);
        return imageService.save(image);
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/notes/ProductLabelListBean.java
package ru.opresent.web.cms.bean.notes;

import org.primefaces.context.RequestContext;
import org.primefaces.event.FileUploadEvent;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.domain.ProductLabel;
import ru.opresent.core.domain.ProductLabelType;
import ru.opresent.core.domain.image.Image;
import ru.opresent.core.domain.image.ImageUse;
import ru.opresent.core.service.ServiceException;
import ru.opresent.core.service.api.ProductLabelService;
import ru.opresent.web.cms.EditingList;
import ru.opresent.web.cms.bean.ImageFileBean;
import ru.opresent.web.cms.component.dialog.EditDialog;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.context.FacesContext;
import javax.validation.ConstraintViolationException;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * User: artem
 * Date: 25.05.14
 * Time: 19:26
 */
@Component("productLabelListBean")
@Scope("view")
public class ProductLabelListBean extends EditingList<ProductLabel> implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.notes.product_label_list";

    @Resource(name = "productLabelService")
    private transient ProductLabelService productLabelService;

    @Resource(name = "imageFileBean")
    private transient ImageFileBean imageFileBean;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    private ProductLabelEditDialog dialog = new ProductLabelEditDialog();

    @PostConstruct
    private void init() {
        reloadList();
    }

    @Override
    public List<ProductLabel> loadList() {
        return productLabelService.getAll().getAll();
    }

    @Override
    public ProductLabelEditDialog getDialog() {
        return dialog;
    }

    @Override
    public void delete() {
        ProductLabel deletingLabel = getSelected();

        try {
            productLabelService.delete(deletingLabel);
        } catch (ServiceException e) {
            messageManager.addErrorMessage(e);
            return;
        }

        messageManager.addInfoMessage(BUNDLE_NAME, "delete_success");
        reloadList();
    }

    // setters & getters

    public List<ProductLabelType> getAvailableLabelTypes() {
        return Arrays.asList(ProductLabelType.values());
    }

    // inner classes

    public class ProductLabelEditDialog extends EditDialog implements Serializable {

        private ProductLabel productLabel;
        private String title;

        @Override
        public void prepareToAdd() {
            productLabel = new ProductLabel();
            title = messageManager.getMessage(BUNDLE_NAME, "add_dialog_title");
        }

        @Override
        public void prepareToEdit() {
            productLabel = new ProductLabel(getSelected());
            title = messageManager.getMessage(BUNDLE_NAME, "edit_dialog_title");
        }

        @Override
        public void save() {
            try {
                productLabelService.save(productLabel);
            } catch (ConstraintViolationException e) {
                messageManager.addErrorMessage(e);
                FacesContext.getCurrentInstance().validationFailed();
                return;
            }

            messageManager.addInfoMessage(BUNDLE_NAME, "save_success");
            reloadList();
            RequestContext.getCurrentInstance().update(Arrays.asList("productLabelListForm", "messages"));
        }

        public void handleImageUpload(FileUploadEvent event) {
            Image image = imageFileBean.saveImage(event.getFile(), ImageUse.PRODUCT_LABEL_IMAGE);
            productLabel.setImage(image);
        }

        @Override
        public String getTitle() {
            return title;
        }

        public ProductLabel getProductLabel() {
            return productLabel;
        }

        public boolean isProductLabelWithDiscount() {
            return productLabel.isWithDiscount();
        }

        public void setProductLabelWithDiscount(boolean withDiscount) {
            productLabel.setWithDiscount(withDiscount);
            if (!withDiscount) {
                productLabel.setDiscountPercent(null);
            }
        }
    }
}

opresent-cms/src/main/java/ru/opresent/web/cms/bean/notes/ProductStatusInfoListBean.java
package ru.opresent.web.cms.bean.notes;

import org.primefaces.context.RequestContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.opresent.core.domain.ProductStatus;
import ru.opresent.core.domain.ProductStatusInfo;
import ru.opresent.core.service.api.ProductStatusService;
import ru.opresent.core.util.EnumHelper;
import ru.opresent.web.cms.EditingList;
import ru.opresent.web.cms.component.dialog.EditDialog;
import ru.opresent.web.cms.util.MessageManager;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.context.FacesContext;
import javax.validation.ConstraintViolationException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * User: artem
 * Date: 25.05.14
 * Time: 19:25
 */
@Component("productStatusInfoListBean")
@Scope("view")
public class ProductStatusInfoListBean extends EditingList<ProductStatusInfo> implements Serializable {

    private static final String BUNDLE_NAME = "ru.opresent.web.cms.i18n.notes.product_status_info_list";

    @Resource(name = "productStatusService")
    private transient ProductStatusService productStatusService;

    @Resource(name = "enumHelper")
    private transient EnumHelper enumHelper;

    @Resource(name = "messageManager")
    private transient MessageManager messageManager;

    private ProductStatusInfoEditDialog dialog = new ProductStatusInfoEditDialog();

    @PostConstruct
    private void init() {
        reloadList();
    }

    @Override
    public List<ProductStatusInfo> loadList() {
        List<ProductStatusInfo> infos = new ArrayList<>(productStatusService.getAll().values());

        for (ProductStatus productStatus : ProductStatus.values()) {
            ProductStatusInfo info = new ProductStatusInfo(productStatus);
            if (!infos.contains(info)) {
                infos.add(info);
            }
        }

        Collections.sort(infos);
        return infos;
    }

    @Override
    public ProductStatusInfoEditDialog getDialog() {
        return dialog;
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Product status info can not be deleted!");
    }

    // inner classes

    public class ProductStatusInfoEditDialog extends EditDialog implements Serializable {

        private ProductStatusInfo statusInfo;
        private String title;

        @Override
        public void prepareToAdd() {
            throw new UnsupportedOperationException("Product status info can not be added!");
        }

        @Override
        public void prepareToEdit() {
            statusInfo = new ProductStatusInfo(getSelected());
            title = messageManager.getMessage(BUNDLE_NAME,
                    "edit_dialog_title", enumHelper.getDescription(statusInfo.getStatus()));
        }

        @Override
        public void save() {
            try {
                productStatusService.save(statusInfo);
            } catch (ConstraintViolationException e) {
                messageManager.addErrorMessage(e);
                FacesContext.getCurrentInstance().validationFailed();
                return;
            }

            messageManager.addInfoMessage(BUNDLE_NAME,
                    "save_success", enumHelper.getDescription(statusInfo.getStatus()));
            reloadList();
            RequestContext.getCurrentInstance().update(Arrays.asList("productStatusInfoListForm", "messages"));
        }

        @Override
        public String getTitle() {
            return title;
        }

        public ProductStatusInfo getStatusInfo() {
            return statusInfo;
        }
    }
}

opresent-cms/src/main/webapp/pages/notes/notes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="/pages/template/template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:p="http://primefaces.org/ui"
                xml:lang="en" lang="en">

    <ui:define name="windowTitle">
        <f:loadBundle var="main_menu" basename="ru.opresent.web.cms.i18n.main_menu"/>
        <h:outputText value="#{main_menu.notes}"/>
    </ui:define>

    <ui:define name="content">
        <style type="text/css">
            .noteTableTitle {
                display: block;
                text-align: left;
                font-size: 20px;
                margin-top: 20px;
            }
        </style>

        <p:panel header="#{main_menu.notes}" collapsed="true" styleClass="pageHeaderPanel"/>

        <ui:include src="product_status_info_list_include.xhtml"/>
        <ui:include src="product_label_list_include.xhtml"/>
    </ui:define>

</ui:composition>

opresent-cms/src/main/webapp/pages/notes/product_label_list_include.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:opresent="http://java.sun.com/jsf/composite/opresent"
                xml:lang="en" lang="en">

    <f:loadBundle var="product_label_list" basename="ru.opresent.web.cms.i18n.notes.product_label_list"/>
    <f:loadBundle var="buttons" basename="ru.opresent.web.cms.i18n.buttons"/>
    <f:loadBundle var="common" basename="ru.opresent.web.cms.i18n.common"/>

    <style type="text/css">
        .productLabelFieldDesc {
            text-align: right;
            padding-right: 10px;
            padding-bottom: 10px;
        }

        .productLabelField {
            text-align: left !important;
            padding-bottom: 10px;
        }

        .productLabelField .ui-inputfield,
        .productLabelField .ui-inputtextarea {
            width: 300px;
        }

        .productLabelField img {
            max-width: 200px;
        }

        .productLabelImageUploader {
            text-align: center;
        }

        .productLabelImage {
            margin-bottom: 20px;
            display: block;
        }
    </style>

    <h:outputText value="#{product_label_list.title}" styleClass="noteTableTitle"/>

    <h:form id="productLabelListForm">
        <p:dataTable id="productLabelsTable" value="#{productLabelListBean.list}"
                     var="productLabel" rowKey="#{productLabel.id}"
                     selection="#{productLabelListBean.selected}" selectionMode="single">

            <f:facet name="header">
                <opresent:editTableButtons id="editTableButtons" editDialogVar="productLabelDialogWidget"
                                      editDialogId=":productLabelDialog" editingList="#{productLabelListBean}"
                                      editTableId=":productLabelListForm:productLabelsTable"
                                      deleteConfirmHeader="#{product_label_list.delete_confirm_header}"
                                      deleteConfirmMsg="#{product_label_list.delete_confirm_msg}"/>
            </f:facet>

            <p:ajax event="rowSelect" update=":productLabelListForm:productLabelsTable:editTableButtons"/>
            <p:ajax event="rowUnselect" update=":productLabelListForm:productLabelsTable:editTableButtons"/>

            <p:column headerText="Id" width="20">
                <h:outputText value="#{productLabel.id}"/>
            </p:column>

            <p:column headerText="#{product_label_list.type}">
                <h:outputText value="#{enumHelper.getDescription(productLabel.type)}"/>
            </p:column>

            <p:column headerText="#{product_label_list.image}">
                <img src="#{imageFileManager.createUrl(productLabel.image)}"/>
            </p:column>

            <p:column headerText="#{product_label_list.with_discount}">
                <p:selectBooleanCheckbox value="#{productLabel.withDiscount}" disabled="true"/>
            </p:column>

            <p:column headerText="#{product_label_list.discount_percent}">
                <h:outputText value="#{productLabel.discountPercent}"/>
            </p:column>

            <p:column headerText="#{product_label_list.default_note}">
                <h:outputText value="#{productLabel.defaultNote}"/>
            </p:column>

        </p:dataTable>
    </h:form>

    <opresent:editDialog id="productLabelDialog" editDialog="#{productLabelListBean.dialog}"
                    widgetVar="productLabelDialogWidget"
                    saveButtonProcess="@(.productLabelGrid :not(.productLabelImageUploader))">

        <h:panelGrid columns="2" columnClasses="productLabelFieldDesc,productLabelField"
                     rendered="#{not empty productLabelListBean.dialog.productLabel}"
                     styleClass="productLabelGrid">

            <h:outputText value="#{product_label_list.type}"/>
            <p:selectOneMenu id="productLabelType"
                             value="#{productLabelListBean.dialog.productLabel.type}">
                <f:selectItems value="#{productLabelListBean.availableLabelTypes}"
                               var="productLabelType"
                               itemValue="#{productLabelType}"
                               itemLabel="#{enumHelper.getDescription(productLabelType)}"/>
            </p:selectOneMenu>

            <h:outputText value="#{product_label_list.image}"/>
            <h:panelGroup>
                <p:fileUpload allowTypes="#{imageFileBean.allowTypesPattern}"
                              invalidFileMessage="#{imageFileBean.invalidFileMessage}"
                              sizeLimit="#{imageFileBean.sizeLimit}"
                              invalidSizeMessage="#{imageFileBean.invalidSizeMessage}"
                              fileUploadListener="#{productLabelListBean.dialog.handleImageUpload}"
                              styleClass="productLabelImageUploader"
                              auto="true" label="#{buttons.define}"
                              update=":messages productLabelImage"/>

                <h:panelGroup id="productLabelImage" styleClass="productLabelImage">
                    <h:outputText value="#{product_label_list.image_not_defined}" styleClass="alarm"
                                  rendered="#{empty productLabelListBean.dialog.productLabel.image}"/>

                    <h:panelGroup rendered="#{not empty productLabelListBean.dialog.productLabel.image}">
                        <img src="#{imageFileManager.createUrl(productLabelListBean.dialog.productLabel.image)}"/>
                    </h:panelGroup>
                </h:panelGroup>
            </h:panelGroup>

            <h:outputText value="#{product_label_list.with_discount}"/>
            <p:selectBooleanCheckbox value="#{productLabelListBean.dialog.productLabelWithDiscount}">
                <p:ajax process="@this" update="@this @(.productLabelDiscountPercent)"/>
            </p:selectBooleanCheckbox>

            <h:panelGroup id="productLabelDiscountPercentFieldDesc" styleClass="productLabelDiscountPercent">
                <h:outputText value="#{product_label_list.discount_percent}"
                              rendered="#{productLabelListBean.dialog.productLabel.withDiscount}"/>
            </h:panelGroup>
            <h:panelGroup id="productLabelDiscountPercentField" styleClass="productLabelDiscountPercent">
                <p:inputText value="#{productLabelListBean.dialog.productLabel.discountPercent}"
                             rendered="#{productLabelListBean.dialog.productLabel.withDiscount}"
                             converterMessage="#{product_label_list.discount_percent_converter_msg}"/>
            </h:panelGroup>

            <h:outputText value="#{product_label_list.default_note}"/>
            <h:panelGroup>
                <p:inputTextarea value="#{productLabelListBean.dialog.productLabel.defaultNote}"
                                 maxlength="#{entitiesConstraints.productLabelNoteMaxLength}"
                                 counter="labelNoteCounter" counterTemplate="#{common.chars_remaining}"/>
                <h:outputText id="labelNoteCounter" styleClass="charsCounter"/>
            </h:panelGroup>
        </h:panelGrid>
    </opresent:editDialog>

</ui:composition>

opresent-cms/src/main/webapp/pages/notes/product_status_info_list_include.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:opresent="http://java.sun.com/jsf/composite/opresent"
                xml:lang="en" lang="en">

    <f:loadBundle var="product_status_info_list" basename="ru.opresent.web.cms.i18n.notes.product_status_info_list"/>
    <f:loadBundle var="common" basename="ru.opresent.web.cms.i18n.common"/>

    <style type="text/css">
        .productStatusInfoFieldDesc {
            text-align: right;
            padding-right: 10px;
            padding-bottom: 10px;
        }

        .productStatusInfoField {
            text-align: left !important;
            padding-bottom: 10px;
        }

        .productStatusInfoField .ui-inputtextarea {
            width: 300px;
        }

    </style>

    <h:outputText value="#{product_status_info_list.title}" styleClass="noteTableTitle"/>

    <h:form id="productStatusInfoListForm">
        <p:dataTable id="productStatusInfoTable" value="#{productStatusInfoListBean.list}"
                     var="productStatusInfo" rowKey="#{productStatusInfo.id}"
                     selection="#{productStatusInfoListBean.selected}" selectionMode="single">

            <f:facet name="header">
                <opresent:editTableButtons id="editTableButtons" editDialogVar="productStatusInfoWidget"
                                      editDialogId=":productStatusInfoDialog" editingList="#{productStatusInfoListBean}"
                                      editTableId=":productStatusInfoListForm:productStatusInfoTable"
                                      renderAddButton="false" renderDeleteButton="false"/>
            </f:facet>

            <p:ajax event="rowSelect" update=":productStatusInfoListForm:productStatusInfoTable:editTableButtons"/>
            <p:ajax event="rowUnselect" update=":productStatusInfoListForm:productStatusInfoTable:editTableButtons"/>

            <p:column headerText="#{product_status_info_list.product_status}">
                <h:outputText value="#{enumHelper.getDescription(productStatusInfo.status)}"/>
            </p:column>

            <p:column headerText="#{product_status_info_list.default_note}">
                <h:outputText value="#{productStatusInfo.defaultNote}"/>
            </p:column>
        </p:dataTable>
    </h:form>

    <opresent:editDialog id="productStatusInfoDialog" editDialog="#{productStatusInfoListBean.dialog}"
                    widgetVar="productStatusInfoWidget">

        <h:panelGrid columns="2" columnClasses="productStatusInfoFieldDesc,productStatusInfoField"
                     rendered="#{not empty productStatusInfoListBean.dialog.statusInfo}">
            <h:outputText value="#{product_status_info_list.product_status}"/>
            <p:inputText value="#{enumHelper.getDescription(productStatusInfoListBean.dialog.statusInfo.status)}"
                         disabled="true"/>

            <h:outputText value="#{product_status_info_list.default_note}"/>
            <h:panelGroup>
                <p:inputTextarea value="#{productStatusInfoListBean.dialog.statusInfo.defaultNote}"
                                 maxlength="#{entitiesConstraints.productStatusNoteMaxLength}"
                                 counter="statusInfoDefaultNoteCounter" counterTemplate="#{common.chars_remaining}"/>
                <h:outputText id="statusInfoDefaultNoteCounter" styleClass="charsCounter"/>
            </h:panelGroup>
        </h:panelGrid>

    </opresent:editDialog>

</ui:composition>